Fixes - unwrapped bug fix + docs and citation changes
nyuglobalties/rddi pull request #10
Opened 2022-09-08 14:30 UTC by dswoulf

- Fix bug in unwrapped nodes that was causing invalid codebooks
- Added mixed content/unwrapped nodes to vignette
- Added instructions to convert codebook to XML in README
- Changed citation to match common/APA author order and added date.

2022-09-08 16:29 UTC, psanker requested changes
Could you provide some unit tests using `testthat` (`usethis::use_testthat()`) to check that the unwrapped bug is fixed?

2022-09-08 16:29 UTC, psanker commented on vignettes/rddi_intro.Rmd
> +Use the `rddi::as_xml()` and `xml2::write_xml` functions to convert to xml and export. If using mixed content nodes you have to replace the html special entities with "<" and ">" before using `xml2::
Why not do this automatically in `as_xml()`?

2022-09-08 19:35 UTC, dswoulf commented on vignettes/rddi_intro.Rmd
> +Use the `rddi::as_xml()` and `xml2::write_xml` functions to convert to xml and export. If using mixed content nodes you have to replace the html special entities with "<" and ">" before using `xml2::
re `rddi::as_xml()` I just wanted to highlight it is a rddi function. Not a big deal, I'll change that back. And yes, I'll create some unit tests.

2022-09-09 14:15 UTC, dswoulf commented
Changes complete - test checking unwrapped validation in multiple spots of the codebook and vignette edit made

2022-09-20 20:47 UTC, psanker approved these changes
LGTM

2022-09-20 20:48 UTC, merged